package com.pteron.player.theme

import androidx.compose.ui.graphics.Color

// Light palette, ported from the Stitch design tokens.
val LightPrimary = Color(0xFF9B4011)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFBB5828)
val LightOnPrimaryContainer = Color(0xFFFFFBFF)
val LightSecondary = Color(0xFF7B573B)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFFFCDAA)
val LightOnSecondaryContainer = Color(0xFF7A553A)
val LightTertiary = Color(0xFF77553A)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFF926D50)
val LightOnTertiaryContainer = Color(0xFFFFFBFF)
val LightBackground = Color(0xFFFFF8F2)
val LightOnBackground = Color(0xFF1E1B16)
val LightSurface = Color(0xFFFFF8F2)
val LightOnSurface = Color(0xFF1E1B16)
val LightSurfaceVariant = Color(0xFFE9E1D8)
val LightOnSurfaceVariant = Color(0xFF56423A)
val LightOutline = Color(0xFF897269)
val LightOutlineVariant = Color(0xFFDDC1B6)
val LightSurfaceContainerLowest = Color(0xFFFFFFFF)
val LightSurfaceContainerLow = Color(0xFFFAF2E9)
val LightSurfaceContainer = Color(0xFFF5EDE4)
val LightSurfaceContainerHigh = Color(0xFFEFE7DE)
val LightSurfaceContainerHighest = Color(0xFFE9E1D8)
val LightError = Color(0xFFBA1A1A)
val LightOnError = Color(0xFFFFFFFF)
val LightErrorContainer = Color(0xFFFFDAD6)
val LightOnErrorContainer = Color(0xFF93000A)
val LightInverseSurface = Color(0xFF34302A)
val LightInverseOnSurface = Color(0xFFF8EFE6)
val LightInversePrimary = Color(0xFFFFB597)

// Dark palette ("Rich Espresso" / "Dark Walnut" family).
val DarkPrimary = Color(0xFFFFB597)
val DarkOnPrimary = Color(0xFF5C1F00)
val DarkPrimaryContainer = Color(0xFF7D2D00)
val DarkOnPrimaryContainer = Color(0xFFFFDBCD)
val DarkSecondary = Color(0xFFEDBD9B)
val DarkOnSecondary = Color(0xFF432B14)
val DarkSecondaryContainer = Color(0xFF603F25)
val DarkOnSecondaryContainer = Color(0xFFFFDCC4)
val DarkTertiary = Color(0xFFEBBD9C)
val DarkOnTertiary = Color(0xFF432C16)
val DarkTertiaryContainer = Color(0xFF5F4027)
val DarkOnTertiaryContainer = Color(0xFFFFDCC4)
val DarkOnBackground = Color(0xFFEDE1D8)
val DarkOnSurface = Color(0xFFEDE1D8)
val DarkSurfaceVariant = Color(0xFF3F332C)
val DarkOnSurfaceVariant = Color(0xFFD3C4B8)
val DarkOutline = Color(0xFF9C8D83)
val DarkOutlineVariant = Color(0xFF52443C)
val DarkSurfaceContainerLowest = Color(0xFF120D0A)
val DarkSurfaceContainerLow = Color(0xFF221B15)
val DarkSurfaceContainer = Color(0xFF2A2119)
val DarkSurfaceContainerHigh = Color(0xFF352B22)
val DarkSurfaceContainerHighest = Color(0xFF40352B)
val DarkInverseSurface = Color(0xFFEDE1D8)
val DarkInverseOnSurface = Color(0xFF34302A)
val DarkInversePrimary = Color(0xFF9B4011)
